### PR TITLE
Feat  implementing mail with official user email

### PR DESCRIPTION
**Pull request by olawalejuwonm**
# Description

Please include a summary of the change and which issue is fixed. Add a reference to the issue that was fixed! 
#79 
Implemented the use of user official email to send email alert to customers

## Type of change
- [x] New feature (non-breaking change which adds functionality)
The image below shows the functionality
Screenshot (10)
Screenshot (11)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by tboy44wiz** [comment]
Can you make the Users Email to be Automatically be added from the API and not being passed on the body parameter.

**Comment by olawalejuwonm** [comment]
@tboy44wiz  this will require authentication, and that wasn't set up for the reminder/email route. That will be another issue entirely, I can create that and work on it

**Comment by tboy44wiz** [comment]
I think that's the best thing to do. We don't want the Shop owner to be putting his/her email everytime he/she want to send a mail to his/her customers. 

Secondly, if possible try and work on the Mail Template design. Design it with your HTML and CSS to look presentable.

**Comment by olawalejuwonm** [comment]
@tboy44wiz okay thank you, can this be merged  so I can kick start that with another issue immediately

**Comment by Megxos** [comment]
This cannot be merged because it's no different from what is already in place.

**Comment by olawalejuwonm** [comment]
@Megxos kindly check the issue here #79  to get full details

**Pull request closed without merging**
