### PR TITLE
MISSING FIELDS ON THE COMPLAINT API #77 RESOLVED

### PR DESCRIPTION
**Pull request by iAmServer**
# Description
MISSING FIELDS ON THE COMPLAINT API #77
Whenever the complaint API is called, it's now returning the user first and last name and user email as shown in the screenshot below

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Screenshot:
Screen Shot 2020-06-26 at 3 47 59 AM

### CODE REVIEW

**Comment by naijauser** [comment]
Please describe what you fixed using the template.

**Comment by iAmServer** [comment]
That's why I link it to the issue I fixed

**Comment by chinazaaa** [comment]
testing

**Comment by naijauser** [comment]
What user token did you use. Token authentication is failing for most users. Why is this?

**Comment by iAmServer** [comment]
I used the JWT token generated for user signup.. I mentioned this in the channel that the authentication system for the API needs lot of improvement.... the auth.js which is expected to be a middle ware is not receiving the token the right way

**Comment by iAmServer** [comment]
Tokens are suppose to be sent with the request header but the middle ware accepts token as an input

**Comment by iAmServer** [comment]
Since it's not the issue assigned to me, I followed the pattern

**Comment by iAmServer** [comment]
Anyways use the token from user signup or login and send it as input

**Comment by naijauser** [comment]
I and @chinazaaa have tested your PR independently and we are getting the same results and they are different from yours. See the screenshot below. 
err

It would help if you could provide some extra context for us.

**Comment by iAmServer** [comment]
https://drive.google.com/file/d/12P20a1uSHROouudk8oiqIKCx-8Y24jun/view?usp=sharing

That's a video showing the test of the issue, it's definitely working fine

**Comment by naijauser** [comment]
It works. Nice work, thanks for sticking with us through it all. You mentioned some issues earlier that you would like us to address. Please send us the issues using the Google form that was sent to the backend channel. Your PR will be merged in a moment. Cheers. 

PS: I'm @naijauser on Slack, feel free to reach out to me.

**Comment by chinazaaa** [comment]
Merging

**Pull request merged**
